<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="public/favicon.ico">
    <link rel="stylesheet" href="public/style/style.css">
    <title>Home | Atea Car Booking</title>
</head>
<body>
    <header class="header">
        <div class="header-left">
            <img src="public/atea-logo.generated.svg" alt="ATEA Logo" class="logo">
        </div>
        <div class="header-right">
            <button class="user-pill" id="userMenuToggle" aria-haspopup="true" aria-expanded="false">
                <span class="user-name">User</span>
                <img src="public/UserIcon.png" alt="User" class="user-avatar">
            </button>
            <div class="user-menu" id="userMenu" hidden>
                <button id="logoutBtn" class="logout-item">Logout</button>
            </div>
        </div>
    </header>

    <!-- Date Selection Section -->
    <div class="date-selection-section">
        <div class="date-inputs-container">
            <h2>When do you need a car?</h2>
            <div class="date-inputs">
                <div class="date-group">
                    <label for="startTime">Start Date & Time</label>
                    <input type="datetime-local" id="startTime" placeholder="Pick start date/time">
                </div>
                <div class="date-group">
                    <label for="endTime">End Date & Time</label>
                    <input type="datetime-local" id="endTime" placeholder="Pick end date/time">
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <!-- Filters Panel -->
        <aside class="filters-panel">
            <h2>Filters</h2>
            
            <div class="filter-group">
                <label>Brands</label>
                <div class="multi-select-wrapper">
                    <select id="brandFilter" class="multi-select">
                        <option value="" disabled selected hidden>Select brands...</option>
                    </select>
                    <div class="multi-select-dropdown" id="brandDropdown"></div>
                </div>
            </div>

            <div class="filter-group">
                <label>Year</label>
                <div class="multi-select-wrapper">
                    <select id="yearFilter" class="multi-select">
                        <option value="" disabled selected hidden>Select years...</option>
                    </select>
                    <div class="multi-select-dropdown" id="yearDropdown"></div>
                </div>
            </div>

            <div class="filter-group">
                <label>Seats</label>
                <div class="multi-select-wrapper">
                    <select id="seatsFilter" class="multi-select">
                        <option value="" disabled selected hidden>Select seats...</option>
                    </select>
                    <div class="multi-select-dropdown" id="seatsDropdown"></div>
                </div>
            </div>

            <div class="filter-group">
                <label>Fuel Type</label>
                <div class="multi-select-wrapper">
                    <select id="fuelFilter" class="multi-select">
                        <option value="" disabled selected hidden>Select fuel types...</option>
                    </select>
                    <div class="multi-select-dropdown" id="fuelDropdown"></div>
                </div>
            </div>

            <button class="filter-button-secondary" id="clearFilters">Clear Filters</button>
        </aside>

        <!-- Main Content -->
        <main class="main-content">
            <div class="cars-grid" id="carsGrid">
                <!-- Car cards will be generated by JavaScript -->
            </div>
        </main>
    </div>

    <!-- Modular JavaScript files loaded in dependency order -->
    <script src="public/js/utils.js"></script>
    <script src="public/js/auth.js"></script>
    <script src="public/js/url-params.js"></script>
    <script src="public/js/filters.js"></script>
    <script src="public/js/cars.js"></script>
    <script src="public/js/script.js"></script>
</body>
</html>
